@startuml viewer

hide circle
!theme mars

class MolstarPartialCharges {
  - plugin: PluginUIContext

  + charges: Charges
  + color: Color
  + type: Type
  + visual: Visual

  + static create(target: string, extensions: object)
  + async load(url: string, format: string, targetWebApp: string)
  + updateColor(name: string, params: object)
  + updateType(name: string, params: object)
}

class Charges {
  + setTypeId(typeId: number)
  + getTypeId(): number
  + getMaxCharge(): number
  + getMethodNames(): string[]
}

class Color {
  + default()
  + alphaFold()
  + relative()
  + absolute(max: number)
}

class Type {
  + isDefaultApplicable(): boolean
  + default()
  + ballAndStick()
  + surface()
}

class Visual {
  + focus(key: object)
}

MolstarPartialCharges --> Type
MolstarPartialCharges --> Color
MolstarPartialCharges --> Charges
MolstarPartialCharges --> Visual

@enduml